version: '3.8'
services:
  db:
      container_name: pg_container
      image: postgres:13.4
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: sales
      ports:
        - "5432:5432"
      expose:
        - 5432
      volumes:
        - pg_data:/var/lib/postgresql/data/
  api:
      build: ./project
      command: uvicorn app.main:app --reload --workers 2 --host 0.0.0.0 --port 8000
      volumes:
        - ./project:/usr/src/app
      ports:
        - 8000:8000
      environment:
        - DATABASE_URL=postgresql://root:root@db:5432/sales
      depends_on:
        - db

volumes:
  pg_data: